name: Publish Release

on:
  push:
    tags:
      - 'v*'
      - 'V*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: install dependencies
        run: npm ci

      - name: Get version number
        id: version_env
        shell: bash
        run: |
          TAG_NAME="${{ github.ref_name }}"
          PURE_VERSION="${TAG_NAME#[vV]}"
          echo "version=$PURE_VERSION" >> $GITHUB_OUTPUT

      - name: Overwrite version in tauri.conf.json
        shell: bash
        run: |
          NEW_VER="${{ steps.version_env.outputs.version }}"
          jq --arg ver "$NEW_VER" '.version = $ver' src-tauri/tauri.conf.json > tmp.json && mv tmp.json src-tauri/tauri.conf.json

      - name: Overwrite version in package.json
        shell: bash
        run: |
          NEW_VER="${{ steps.version_env.outputs.version }}"
          jq --arg ver "$NEW_VER" '.version = $ver' package.json > tmp.json && mv tmp.json package.json

      - name: Overwrite version in package-lock.json
        shell: bash
        run: |
          NEW_VER="${{ steps.version_env.outputs.version }}"
          jq --arg ver "$NEW_VER" '.version = $ver | .packages."".version = $ver' package-lock.json > tmp.json && mv tmp.json package-lock.json

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: | 
            <img width="89" height="89" alt="Square89x89Logo" src="https://github.com/user-attachments/assets/3fd83aff-b7a7-45f5-b739-b06e235b0661" />

            ## **SimpBangumi** by SimpERROR_

            非官方客户端。
            SimpBangumi 不内置、不提供、亦不分发任何 Live2D 角色模型及 Live2D Cubism SDK 核心运行时。
          releaseDraft: true
          prerelease: false