name: "Publish Release"

on:
  push:
    tags:
      - 'v*' # 当你推送形如 v1.0.0 的 tag 时触发

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] 

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: install dependencies
        run: npm install

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Bangumi Client ${{ github.ref_name }}"
          releaseBody: "自动生成的打包版本，请下载对应平台的安装包。"
          releaseDraft: true
          prerelease: false